require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AudioFilesTagsController do

  # This should return the minimal set of attributes required to create a valid
  # AudioFilesTag. As you add validations to AudioFilesTag, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AudioFilesTagsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all audio_files_tags as @audio_files_tags" do
      audio_files_tag = AudioFilesTag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:audio_files_tags).should eq([audio_files_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested audio_files_tag as @audio_files_tag" do
      audio_files_tag = AudioFilesTag.create! valid_attributes
      get :show, {:id => audio_files_tag.to_param}, valid_session
      assigns(:audio_files_tag).should eq(audio_files_tag)
    end
  end

  describe "GET new" do
    it "assigns a new audio_files_tag as @audio_files_tag" do
      get :new, {}, valid_session
      assigns(:audio_files_tag).should be_a_new(AudioFilesTag)
    end
  end

  describe "GET edit" do
    it "assigns the requested audio_files_tag as @audio_files_tag" do
      audio_files_tag = AudioFilesTag.create! valid_attributes
      get :edit, {:id => audio_files_tag.to_param}, valid_session
      assigns(:audio_files_tag).should eq(audio_files_tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AudioFilesTag" do
        expect {
          post :create, {:audio_files_tag => valid_attributes}, valid_session
        }.to change(AudioFilesTag, :count).by(1)
      end

      it "assigns a newly created audio_files_tag as @audio_files_tag" do
        post :create, {:audio_files_tag => valid_attributes}, valid_session
        assigns(:audio_files_tag).should be_a(AudioFilesTag)
        assigns(:audio_files_tag).should be_persisted
      end

      it "redirects to the created audio_files_tag" do
        post :create, {:audio_files_tag => valid_attributes}, valid_session
        response.should redirect_to(AudioFilesTag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved audio_files_tag as @audio_files_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        AudioFilesTag.any_instance.stub(:save).and_return(false)
        post :create, {:audio_files_tag => {}}, valid_session
        assigns(:audio_files_tag).should be_a_new(AudioFilesTag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AudioFilesTag.any_instance.stub(:save).and_return(false)
        post :create, {:audio_files_tag => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested audio_files_tag" do
        audio_files_tag = AudioFilesTag.create! valid_attributes
        # Assuming there are no other audio_files_tags in the database, this
        # specifies that the AudioFilesTag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AudioFilesTag.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => audio_files_tag.to_param, :audio_files_tag => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested audio_files_tag as @audio_files_tag" do
        audio_files_tag = AudioFilesTag.create! valid_attributes
        put :update, {:id => audio_files_tag.to_param, :audio_files_tag => valid_attributes}, valid_session
        assigns(:audio_files_tag).should eq(audio_files_tag)
      end

      it "redirects to the audio_files_tag" do
        audio_files_tag = AudioFilesTag.create! valid_attributes
        put :update, {:id => audio_files_tag.to_param, :audio_files_tag => valid_attributes}, valid_session
        response.should redirect_to(audio_files_tag)
      end
    end

    describe "with invalid params" do
      it "assigns the audio_files_tag as @audio_files_tag" do
        audio_files_tag = AudioFilesTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AudioFilesTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => audio_files_tag.to_param, :audio_files_tag => {}}, valid_session
        assigns(:audio_files_tag).should eq(audio_files_tag)
      end

      it "re-renders the 'edit' template" do
        audio_files_tag = AudioFilesTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AudioFilesTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => audio_files_tag.to_param, :audio_files_tag => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested audio_files_tag" do
      audio_files_tag = AudioFilesTag.create! valid_attributes
      expect {
        delete :destroy, {:id => audio_files_tag.to_param}, valid_session
      }.to change(AudioFilesTag, :count).by(-1)
    end

    it "redirects to the audio_files_tags list" do
      audio_files_tag = AudioFilesTag.create! valid_attributes
      delete :destroy, {:id => audio_files_tag.to_param}, valid_session
      response.should redirect_to(audio_files_tags_url)
    end
  end

end
