require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ListHeadsController do

  # This should return the minimal set of attributes required to create a valid
  # ListHead. As you add validations to ListHead, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ListHeadsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all list_heads as @list_heads" do
      list_head = ListHead.create! valid_attributes
      get :index, {}, valid_session
      assigns(:list_heads).should eq([list_head])
    end
  end

  describe "GET show" do
    it "assigns the requested list_head as @list_head" do
      list_head = ListHead.create! valid_attributes
      get :show, {:id => list_head.to_param}, valid_session
      assigns(:list_head).should eq(list_head)
    end
  end

  describe "GET new" do
    it "assigns a new list_head as @list_head" do
      get :new, {}, valid_session
      assigns(:list_head).should be_a_new(ListHead)
    end
  end

  describe "GET edit" do
    it "assigns the requested list_head as @list_head" do
      list_head = ListHead.create! valid_attributes
      get :edit, {:id => list_head.to_param}, valid_session
      assigns(:list_head).should eq(list_head)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ListHead" do
        expect {
          post :create, {:list_head => valid_attributes}, valid_session
        }.to change(ListHead, :count).by(1)
      end

      it "assigns a newly created list_head as @list_head" do
        post :create, {:list_head => valid_attributes}, valid_session
        assigns(:list_head).should be_a(ListHead)
        assigns(:list_head).should be_persisted
      end

      it "redirects to the created list_head" do
        post :create, {:list_head => valid_attributes}, valid_session
        response.should redirect_to(ListHead.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved list_head as @list_head" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListHead.any_instance.stub(:save).and_return(false)
        post :create, {:list_head => {}}, valid_session
        assigns(:list_head).should be_a_new(ListHead)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListHead.any_instance.stub(:save).and_return(false)
        post :create, {:list_head => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested list_head" do
        list_head = ListHead.create! valid_attributes
        # Assuming there are no other list_heads in the database, this
        # specifies that the ListHead created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ListHead.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => list_head.to_param, :list_head => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested list_head as @list_head" do
        list_head = ListHead.create! valid_attributes
        put :update, {:id => list_head.to_param, :list_head => valid_attributes}, valid_session
        assigns(:list_head).should eq(list_head)
      end

      it "redirects to the list_head" do
        list_head = ListHead.create! valid_attributes
        put :update, {:id => list_head.to_param, :list_head => valid_attributes}, valid_session
        response.should redirect_to(list_head)
      end
    end

    describe "with invalid params" do
      it "assigns the list_head as @list_head" do
        list_head = ListHead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListHead.any_instance.stub(:save).and_return(false)
        put :update, {:id => list_head.to_param, :list_head => {}}, valid_session
        assigns(:list_head).should eq(list_head)
      end

      it "re-renders the 'edit' template" do
        list_head = ListHead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListHead.any_instance.stub(:save).and_return(false)
        put :update, {:id => list_head.to_param, :list_head => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested list_head" do
      list_head = ListHead.create! valid_attributes
      expect {
        delete :destroy, {:id => list_head.to_param}, valid_session
      }.to change(ListHead, :count).by(-1)
    end

    it "redirects to the list_heads list" do
      list_head = ListHead.create! valid_attributes
      delete :destroy, {:id => list_head.to_param}, valid_session
      response.should redirect_to(list_heads_url)
    end
  end

end
