require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LyricsController do

  # This should return the minimal set of attributes required to create a valid
  # Lyric. As you add validations to Lyric, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LyricsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lyrics as @lyrics" do
      lyric = Lyric.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lyrics).should eq([lyric])
    end
  end

  describe "GET show" do
    it "assigns the requested lyric as @lyric" do
      lyric = Lyric.create! valid_attributes
      get :show, {:id => lyric.to_param}, valid_session
      assigns(:lyric).should eq(lyric)
    end
  end

  describe "GET new" do
    it "assigns a new lyric as @lyric" do
      get :new, {}, valid_session
      assigns(:lyric).should be_a_new(Lyric)
    end
  end

  describe "GET edit" do
    it "assigns the requested lyric as @lyric" do
      lyric = Lyric.create! valid_attributes
      get :edit, {:id => lyric.to_param}, valid_session
      assigns(:lyric).should eq(lyric)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lyric" do
        expect {
          post :create, {:lyric => valid_attributes}, valid_session
        }.to change(Lyric, :count).by(1)
      end

      it "assigns a newly created lyric as @lyric" do
        post :create, {:lyric => valid_attributes}, valid_session
        assigns(:lyric).should be_a(Lyric)
        assigns(:lyric).should be_persisted
      end

      it "redirects to the created lyric" do
        post :create, {:lyric => valid_attributes}, valid_session
        response.should redirect_to(Lyric.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lyric as @lyric" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lyric.any_instance.stub(:save).and_return(false)
        post :create, {:lyric => {}}, valid_session
        assigns(:lyric).should be_a_new(Lyric)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lyric.any_instance.stub(:save).and_return(false)
        post :create, {:lyric => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lyric" do
        lyric = Lyric.create! valid_attributes
        # Assuming there are no other lyrics in the database, this
        # specifies that the Lyric created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lyric.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lyric.to_param, :lyric => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lyric as @lyric" do
        lyric = Lyric.create! valid_attributes
        put :update, {:id => lyric.to_param, :lyric => valid_attributes}, valid_session
        assigns(:lyric).should eq(lyric)
      end

      it "redirects to the lyric" do
        lyric = Lyric.create! valid_attributes
        put :update, {:id => lyric.to_param, :lyric => valid_attributes}, valid_session
        response.should redirect_to(lyric)
      end
    end

    describe "with invalid params" do
      it "assigns the lyric as @lyric" do
        lyric = Lyric.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lyric.any_instance.stub(:save).and_return(false)
        put :update, {:id => lyric.to_param, :lyric => {}}, valid_session
        assigns(:lyric).should eq(lyric)
      end

      it "re-renders the 'edit' template" do
        lyric = Lyric.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lyric.any_instance.stub(:save).and_return(false)
        put :update, {:id => lyric.to_param, :lyric => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lyric" do
      lyric = Lyric.create! valid_attributes
      expect {
        delete :destroy, {:id => lyric.to_param}, valid_session
      }.to change(Lyric, :count).by(-1)
    end

    it "redirects to the lyrics list" do
      lyric = Lyric.create! valid_attributes
      delete :destroy, {:id => lyric.to_param}, valid_session
      response.should redirect_to(lyrics_url)
    end
  end

end
